spring:
    application:
        name: vision
    datasource:
        url: jdbc:mysql://localhost:3306/datawarehouse?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: vision
        password: vision
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        validate-on-migrate: true
        enabled: true
        # validate-on-migrate: false
        baseline-on-migrate: true
        # locations: classpath:db/migration

server:
  error:
    include-message: always