spring:
    application:
        name: vision
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    flyway:
        enabled: true
        baseline-on-migrate: true

server:
  error:
    include-message: always