spring:
    application:
        name: vision
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        validate-on-migrate: true
        enabled: true
        baseline-on-migrate: true

server:
  error:
    include-message: always