spring:

    springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

springdoc:
  swagger-ui:
    url: /v3/api-docs
    operationsSorter: alpha
    tagsSorter: alpha

server:
  error:
    include-message: always