spring:
    application:
        name: vision
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 30
            minimum-idle: 5
            idle-timeout: 600000
            max-lifetime: 1800000
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        validate-on-migrate: true
        enabled: true
        baseline-on-migrate: true
    springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      url: /v3/api-docs
      operationsSorter: alpha
      tagsSorter: alpha

server:
  error:
    include-message: always
