services:
  mysql:
    image: 'mysql:8.0.41-debian'
    container_name: vision-back-mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_URL=${DB_URL}'
    ports:
      - '3307:3306'
    volumes:
      - .mysql:/var/lib/mysql
