services:
  postgresql:
    image: postgres:12
    container_name: vision-back-postgres
    environment:
      POSTGRES_USER: vision
      POSTGRES_PASSWORD: vision
      POSTGRES_DB: datawarehouse
      PGDATA: /data/postgres
    ports:
      - '5433:5432'
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - qtsw-network
      
  sonarqube:
    image: sonarqube:community
    container_name: vision-back-sonarqube
    depends_on:
      - postgresql
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/datawarehouse
      SONAR_JDBC_USERNAME: vision
      SONAR_JDBC_PASSWORD: vision
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9001:9000"
    networks:
      - qtsw-network

volumes:
  postgresql:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks: 
  qtsw-network:
    driver: bridge
