name: Build_test

on:
  push:
    branches:       
      - "main"
      - "VSN-*"
      - "Sprint-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Change directory to vision_back
      run: cd vision_back
    
    - name: Build with Maven
      working-directory: vision_back
      run: mvn -B clean package --file pom.xml
      env:
        DB_URL: ${{ secrets.DB_URL_AZURE }}
        DB_USERNAME: ${{ secrets.DB_USER_AZURE }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_AZURE }}
        SONAR_JDBC_URL: ${{ secrets.SONAR_JDBC_URL }}
        SONAR_JDBC_USERNAME: ${{ secrets.SONAR_JDBC_USERNAME }}
        SONAR_JDBC_PASSWORD: ${{ secrets.SONAR_JDBC_PASSWORD }}
