name: Java CI with Maven

on:
  push:
    branches: [ "Sprint-1","Sprint-2", "Sprint-3" ]
  pull_request:
    branches: [ "Sprint-1","Sprint-2", "Sprint-3" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file vision_back/pom.xml

    - name: Run tests
      run: mvn test --file vision_back/pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v1
