name: Java CI with Maven

on:
  push:
    branches: [ "Sprint-1","Sprint-2", "Sprint-3" ]
  pull_request:
    branches: [ "Sprint-1","Sprint-2", "Sprint-3" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Change directory to vision_back
      run: cd vision_back
    
    - name: Build with Maven
      working-directory: vision_back
      run: mvn -B clean package --file pom.xml
      env:
        DB_URL: ${{ secrets.POSTGRES_URL }}
        DB_USERNAME: ${{ secrets.POSTGRES_USER }}
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SONAR_JDBC_URL: ${{ secrets.SONAR_JDBC_URL }}
        SONAR_JDBC_USERNAME: ${{ secrets.SONAR_JDBC_USERNAME }}
        SONAR_JDBC_PASSWORD: ${{ secrets.SONAR_JDBC_PASSWORD }}


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      with:
        directory: vision_back
        token: ${{ secrets.SECRET_TOKEN }}
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  
  merge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Set up Git for merge
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout the ${{ github.base_ref }} branch
        run: |
          git checkout ${{ github.base_ref }}

      - name: Checkout the ${{ github.head_ref }} branch
        run: |
          git checkout -b ${{ github.head_ref }} origin/${{ github.head_ref }}

      - name: Merge ${{ github.head_ref }} to ${{ github.base_ref }}
        run: |
          git checkout ${{ github.base_ref }}
          git merge ${{ github.head_ref }} --no-ff -m "${{ github.head_ref }} - merge: Merge branch ${{ github.head_ref }} into ${{ github.base_ref }}"
          git push origin ${{ github.base_ref }}
