name: Merge_pull_request

on:
  workflow_run:
    workflows: ["Build_pull_request"]
    types: [completed]

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/install.sh | bash
          gh --version

      - name: Find pull request and enable auto-merge
        run: |
          PR_NUMBER=$(gh pr list --state open --json number,headRefName --jq \
            ".[] | select(.headRefName == \"${{ github.event.workflow_run.head_branch }}\") | .number")

          echo "Found PR number: $PR_NUMBER"

          gh pr merge "$PR_NUMBER" \
            --repo "$GITHUB_REPOSITORY" \
            --auto \
            --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}